### ISSUE TITLE
Issue with time when using a rotated screen

### ISSUE THREAD

**Issue by hawai50** [andrewdelph/python-slideshow-with-time-and-weather#1]
Hi guys, I'm using this with a rotated widescreen monitor. It starts off fine, however everytime a minute moves on with the clock, it overprints the next time onto the previous time. This behavoir is also happening with the weather and date too. T

If the /boot/config.txt is edited to rotate the screen into a portrait mode (display_rotate=1 or display_rotate=3), the weather, date and time keep printing over themselves on every update, so you end up with a layered mess of text/numbers. Please can you help?

**Comment by hawai50** [comment]
Just to add to this, it's an issue with the whole overlay. If the /boot/config.txt is edited to rotate the screen into a portrait mode (display_rotate=1 or display_rotate=3), the weather, date and time keep printing over themselves on every update, so you end up with a layered mess of text/numbers. Please can you help?

**Comment by andrewdelph** [comment]
Hey @hawai50, does adding this line `screen.fill((0,0,0))` to [this](https://github.com/andrewdelph/python-slideshow-with-time-and-weather/blob/f28cbf32e82e8d1707c248010989ea7457f7506a/ss.py#L127) fix the issue?

**Comment by hawai50** [comment]
Thanks so much for coming back to me Andrew, yes it's exactly that issue. 

I've added the code to where you referenced just above the image = pygame.image.load line. and it's fixed it. You absolute legend! Thank you so much for taking the time not only to create this, but to help me out too personally.

**Comment by andrewdelph** [comment]
no problem. happy to help and see that someone is using it!

**Comment by hawai50** [comment]
I hope you'll be pleased to know that I'm using it to help promote events
in a little village not for profit social club in Cornwall. It looks fab. I
have a raspberry pi zero hooked up to an old dell ips monitor I picked up
for £10 :)

**Comment by hawai50** [comment]
Here's a little demo. As you know, I needed it to run in portrait mode.
It's so we could pop it in the window successfully (plus I think it stands
out more as you're not used to seeing a screen in that format). Not sure if
I can post the link to the video in my google drive, but here you go:
https://drive.google.com/file/d/1-3VIcRid0DnFtXFfl8-PTFGcT7yVY1Hu/view?usp=sharing

**Comment by andrewdelph** [comment]
That looks great, good work! Thank you for sharing this with me!! also I thought you were talking about Cornwall Ontario, which is pretty close to me. looks like you across the big pond. Best of luck to you!
